repositories {
    flatDir {dirs 'lib'}
}
dependencies {
    compile project(':core')
    compile files('/tmp/spigot1122/out/spigot-1.12.2.jar')
    compile 'junit:junit:4.11'
    compile 'com.sk89q.worldedit:worldedit-bukkit:6.1.4-SNAPSHOT'
    compile 'com.sk89q.worldedit:worldedit-core:6.1.4-SNAPSHOT'
    compile files('../lib/ProtocolLib-API-4.4.0.jar')
    compile 'co.aikar:fastutil-lite:1.0'
}

sourceSets.main.java {
    // This build targets Bukkit/Spigot 1.12.2 only.
    exclude 'com/boydti/fawe/bukkit/v1_7/**'
    exclude 'com/boydti/fawe/bukkit/v1_8/**'
    exclude 'com/boydti/fawe/bukkit/v1_9/**'
    exclude 'com/boydti/fawe/bukkit/v1_10/**'
    exclude 'com/boydti/fawe/bukkit/v1_11/**'
    exclude 'com/boydti/fawe/bukkit/filter/WorldGuardFilter.java'
    exclude 'com/boydti/fawe/bukkit/filter/GriefPreventionFilter.java'
    exclude 'com/boydti/fawe/bukkit/regions/Worldguard.java'
    exclude 'com/boydti/fawe/bukkit/regions/PlotMeFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/TownyFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/FactionsFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/FactionsOneFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/ResidenceFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/GriefPreventionFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/ASkyBlockHook.java'
    exclude 'com/boydti/fawe/bukkit/util/VaultUtil.java'
    exclude 'com/boydti/fawe/bukkit/util/image/BukkitImageViewer.java'
    exclude 'com/boydti/fawe/bukkit/listener/BukkitImageListener.java'
}

sourceSets.main.java {
    exclude 'com/boydti/fawe/bukkit/filter/WorldGuardFilter.java'
    exclude 'com/boydti/fawe/bukkit/filter/GriefPreventionFilter.java'
    exclude 'com/boydti/fawe/bukkit/regions/Worldguard.java'
    exclude 'com/boydti/fawe/bukkit/regions/PlotMeFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/TownyFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/FactionsFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/FactionsOneFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/ResidenceFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/GriefPreventionFeature.java'
    exclude 'com/boydti/fawe/bukkit/regions/ASkyBlockHook.java'
    exclude 'com/boydti/fawe/bukkit/util/VaultUtil.java'
    exclude 'com/boydti/fawe/bukkit/util/image/BukkitImageViewer.java'
    exclude 'com/boydti/fawe/bukkit/listener/BukkitImageListener.java'
    exclude 'com/boydti/fawe/bukkit/v1_7/**'
    exclude 'com/boydti/fawe/bukkit/v1_9/**'
    exclude 'com/boydti/fawe/bukkit/v1_10/**'
    exclude 'com/boydti/fawe/bukkit/v1_11/**'
}

clean { delete "../target" }

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from('src/main/resources') {
        include 'plugin.yml'
        expand(
                name: project.parent.name,
                version: project.parent.version
        )
    }
}

tasks.named('jar') {
    archiveFileName = "fawe-bukkit-${project.parent.version}.jar"
    destinationDirectory = file '../mvn/com/boydti/fawe-bukkit/' + project.parent.version
}
task createPom {
    doLast {
    pom {
        project {
            groupId 'com.boydti'
            artifactId 'fawe-bukkit'
            version project.parent.version
        }
    }
    .getEffectivePom()
            .setDependencies(new ArrayList<>())
            .writeTo("../mvn/com/boydti/fawe-bukkit/${project.parent.version}/fawe-bukkit-${project.parent.version}.pom")
    pom {
        project {
            groupId 'com.boydti'
            artifactId 'fawe-bukkit'
            version 'latest'
        }
    }
    .getEffectivePom()
            .setDependencies(new ArrayList<>())
            .writeTo("../mvn/com/boydti/fawe-bukkit/latest/fawe-bukkit-latest.pom")
    }
}
task copyFiles {
    doLast {
        copy {
            from "../mvn/com/boydti/fawe-bukkit/${project.parent.version}/"
            into '../mvn/com/boydti/fawe-bukkit/latest/'
            include('*.jar')
            rename ("fawe-bukkit-${project.parent.version}.jar", 'fawe-bukkit-latest.jar')
        }
    }
}

apply plugin: 'com.gradleup.shadow'
// We only want the shadow jar produced
shadowJar {
    dependencies {
        include(dependency('com.github.luben:zstd-jni:1.1.1'))
        include(dependency('co.aikar:fastutil-lite:1.0'))
        include(dependency(':core'))
    }
    archiveFileName = "${parent.name}-${project.name}-${parent.version}.jar"
    destinationDirectory = file '../target'
    relocate('com.google.gson', 'com.sk89q.worldedit.internal.gson')
}
shadowJar.doLast {
    task ->
        ant.checksum file: task.archivePath
}

build.dependsOn(shadowJar);
